NodeVersion="16.20.1"
nodeBuildCommandsFile="/tmp/zipdeploy/extracted/oryx-build-commands.txt"
Frameworks="React"
compressedNodeModulesFile="node_modules.tar.gz"
OutputDirPath="build"
OperationId="16a94072a022c7f1"
SourceDirectoryInBuildContainer="/tmp/8db82fdad414bd4"
PlatformName="nodejs"
CompressDestinationDir="false"
