openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/CONTACTCENTERSERVICE/GNIECloudFiles/1.0.0
  - description: Local Development Server
    url: http://localhost:3001
  - description: Production Server
    url: https://api.gniecloud.com/
info:
  description: GNIECloud MaintenanceBanner API
  version: "1.0.0"
  title: GNIECloud MaintenanceBanner API
  contact:
    email: contactcenterservices@igt.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Maintenance-Banner
    description: API operations for maintenance banners

paths:
  /api/maintenance/banner/details:
    get:
      tags:
        - Maintenance-Banner
      summary: Get maintenance banner details
      operationId: getMaintenanceBannerDetails
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                enabled: true
                maintenanceDetails: {}
  /api/maintenance/banner:
    post:
      tags:
        - Maintenance-Banner
      summary: Get maintenance status and schedule
      operationId: getMaintenanceStatus
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                enabled: false
                date: '2023-07-21'
                startTime: '12:00'
                endTime: '14:00'


components:
  schemas:
    MaintenanceBannerDetails:
      type: object
      properties:
        enabled:
          type: boolean
        maintenanceDetails:
          type: object
        
    MaintenanceStatus:
      type: object
      properties:
        enabled:
          type: boolean
        date:
          type: string
          format: date
        startTime:
          type: string
          format: time
        endTime:
          type: string
          format: time