openapi: 3.0.0
servers:
  - description: Local Development Server
    url: http://localhost:3001
  - description: Production Server
    url: https://api.gniecloud.com/
info:
  description: |
    GNIECloud Reporting API

    **Authentication**: Bearer token is required for all endpoints.

  version: "1.0.0"
  title: GNIECloud Reporting API
  contact:
    email: contactcenterservices@igt.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Data-Operations
    description: Data operations for Forms
  - name: Forms-Submissions
    description: Forms data operations

paths:
  /v1/reporting/{businessUnit}/{form}/all:
    get:
      tags:
        - Data-Operations
      summary: Fetch all GNIECloud Forms submissions
      operationId: getForms
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    FormsName:
                      type: string
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

  

components:
  schemas:
    RRFData:
      type: array
      properties:
        id:
          type: string
        startTime:
          type: string
        completionTime:
          type: string
        emailAddress:
          type: string
        name:
          type: string
        rmaNumber:
          type: string
        assetTag:
          type: string
        serialNumber:
          type: string
        failureMode:
          type: string
        solution:
          type: string
        secondSolution:
          type: string
        partsUsed:
          type: string
        status:
          type: string
        workTime:
          type: string
        comments:
          type: string
        jurisdiction:
          type: string
        stoNumber:
          type: string
        quantityRepaired:
          type: string
        itemNumber:
          type: string
    
    FST:
      type: Array
      properties:
        articleID:
          type: integer
        FormsName:
          type: string
        FormsType:
          type: string
    
    Forms:
      type: object
      properties:
        articleID:
          type: integer
        FormsName:
          type: string
        FormsType:
          type: string
