openapi: 3.0.0
info:
  title: Weather API
  version: 1.0.0
  description: Simple weather API for retrieving weather information.
servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.weather.com
    description: Production server
paths:
  /weather:
    get:
      summary: Get weather information
      parameters:
        - name: city
          in: query
          description: The city for which to retrieve weather information
          required: true
          schema:
            type: string
        - name: country
          in: query
          description: The country code for the city
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  city:
                    type: string
                  country:
                    type: string
                  temperature:
                    type: number
                  humidity:
                    type: number
                  wind_speed:
                    type: number
        '400':
          description: Bad request
        '404':
          description: City not found
        '500':
          description: Internal Server Error
  /forecast:
    get:
      summary: Get weather forecast
      parameters:
        - name: city
          in: query
          description: The city for which to retrieve the weather forecast
          required: true
          schema:
            type: string
        - name: country
          in: query
          description: The country code for the city
          required: true
          schema:
            type: string
        - name: days
          in: query
          description: Number of days for the forecast
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 7
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  city:
                    type: string
                  country:
                    type: string
                  forecast:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                        temperature:
                          type: number
                        humidity:
                          type: number
                        wind_speed:
                          type: number
        '400':
          description: Bad request
        '404':
          description: City not found
        '500':
          description: Internal Server Error
  /alerts:
    get:
      summary: Get weather alerts
      parameters:
        - name: city
          in: query
          description: The city for which to retrieve weather alerts
          required: true
          schema:
            type: string
        - name: country
          in: query
          description: The country code for the city
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  city:
                    type: string
                  country:
                    type: string
                  alerts:
                    type: array
                    items:
                      type: object
                      properties:
                        alert_type:
                          type: string
                        description:
                          type: string
                        severity:
                          type: string
        '400':
          description: Bad request
        '404':
          description: City not found
        '500':
          description: Internal Server Error
  /historical:
    get:
      summary: Get historical weather data
      parameters:
        - name: city
          in: query
          description: The city for which to retrieve historical weather data
          required: true
          schema:
            type: string
        - name: country
          in: query
          description: The country code for the city
          required: true
          schema:
            type: string
        - name: date
          in: query
          description: The date for which to retrieve historical weather data
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  city:
                    type: string
                  country:
                    type: string
                  date:
                    type: string
                    format: date
                  temperature:
                    type: number
                  humidity:
                    type: number
                  wind_speed:
                    type: number
        '400':
          description: Bad request
        '404':
          description: Data not found
        '500':
          description: Internal Server Error
components:
  schemas:
    Weather:
      type: object
      properties:
        city:
          type: string
        country:
          type: string
        temperature:
          type: number
        humidity:
          type: number
        wind_speed:
          type: number
    Forecast:
      type: object
      properties:
        date:
          type: string
          format: date
        temperature:
          type: number
        humidity:
          type: number
        wind_speed:
          type: number
    Alert:
      type: object
      properties:
        alert_type:
          type: string
        description:
          type: string
        severity:
          type: string
    HistoricalWeather:
      type: object
      properties:
        city:
          type: string
        country:
          type: string
        date:
          type: string
          format: date
        temperature:
          type: number
        humidity:
          type: number
        wind_speed:
          type: number